### ISSUE TITLE
[Helm] Duplicate allowedHostPaths in psp.yaml

### ISSUE THREAD

**Issue by RedBlackThunder** [wallarm/sysbindings#4]
The key allowedHostPaths in duplicated in the template psp.yaml, which results in an error message with helm.

Kind regards,
Florian

**Comment by MrEcco** [comment]
Thank you for your issue

Field duplication in YAML does not produce errors, and even for validation by jsonschema it is invisible. Nevertheless, this can confuse while reading the chart. We will fix it soon.

```bash
set -e

# Is YAML valid?
helm template . | yq . >/dev/null

# Is manifests valid?
helm template . | kubeval --schema-location \
    https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/ 
```

**Comment by MrEcco** [comment]
@RedBlackThunder

Now you able to see v0.9.5 release. Also we have add the info about helm registry that we deploy this chart in.

**Comment by RedBlackThunder** [comment]
Thx for fixing.

I do not know why, but we are using FluxCD and Helm and it was complaining about that duplicate key.
